import { NextPageContext, type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { getSession, signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import Chat from "../components/Chat";
import Auth from "../components/Auth";

const Home: NextPage = () => {
  const { data: session, status } = useSession();
  console.log("HERE IS SESSION", session);

  /**
   * Reload session to obtain new username
   */
  const reloadSession = () => {
    const event = new Event("visibilitychange");
    document.dispatchEvent(event);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {session?.user?.username ? (
            <Chat session={session} />
          ) : (
            <Auth session={session} reloadSession={reloadSession} />
          )}
        </div>
      </main>
    </>
  );
};

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}

export default Home;
